// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {lnrpc} from '../models';
import {frontend} from '../models';

export function GetDefaultLndDir():Promise<string>;

export function GetLndAdminMacaroonPath():Promise<string>;

export function GetLndChainInfo(arg1:string):Promise<main.ChainInfo>;

export function GetLndPath():Promise<string>;

export function GetLndRest():Promise<string>;

export function GetState():Promise<lnrpc.GetStateResponse>;

export function OpenFileSelector(arg1:frontend.OpenDialogOptions):Promise<string>;

export function RunLnd():Promise<void>;

export function StopLnd():Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function VerifyConfig(arg1:string,arg2:string):Promise<void>;
