// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenSeed(arg1) {
  return window['go']['main']['App']['GenSeed'](arg1);
}

export function GetDefaultLndDir() {
  return window['go']['main']['App']['GetDefaultLndDir']();
}

export function GetLndAdminMacaroonPath() {
  return window['go']['main']['App']['GetLndAdminMacaroonPath']();
}

export function GetLndChainInfo(arg1) {
  return window['go']['main']['App']['GetLndChainInfo'](arg1);
}

export function GetLndPath() {
  return window['go']['main']['App']['GetLndPath']();
}

export function GetLndRest() {
  return window['go']['main']['App']['GetLndRest']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InitWallet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InitWallet'](arg1, arg2, arg3, arg4);
}

export function OpenDirectorySelector(arg1) {
  return window['go']['main']['App']['OpenDirectorySelector'](arg1);
}

export function OpenFileSelector(arg1) {
  return window['go']['main']['App']['OpenFileSelector'](arg1);
}

export function RunLnd() {
  return window['go']['main']['App']['RunLnd']();
}

export function StopLnd() {
  return window['go']['main']['App']['StopLnd']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function VerifyConfig(arg1, arg2) {
  return window['go']['main']['App']['VerifyConfig'](arg1, arg2);
}
