name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"
  PRERELEASE: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'LND-Desk'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'LND-Desk'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'LND-Desk'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Determine PRERELEASE
        id: PRERELEASE
        env:
          PRERELEASE: false
        if: match(github.ref_name, '^v[0-9]+\\.[0-9]+\\.[0-9]+$')
        run: echo "This is a stable release."

      - name: Build wails
        uses: btclayer2/wails-build-action@v0.0.7
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          prerelease: ${{ env.PRERELEASE }}
          package: true
          node-version: '22.8.0'
          go-version: '1.23'
          deno-build: 'npm i -g pnpm'
          deno-version: '2.1.4'
          deno-working-directory: './'
          tags: 'autopilotrpc signrpc walletrpc chainrpc invoicesrpc neutrinorpc routerrpc watchtowerrpc monitoring peersrpc kvdb_postrgres kvdb_sqlite kvdb_etcd'