name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'LND-Desk'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'LND-Desk'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'LND Desk'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: btclayer2/wails-build-action@v0.0.6
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          node-version: '22.8.0'
          go-version: '1.23'
          deno-build: 'npm i -g pnpm'
          deno-version: '2.1.4'
          deno-working-directory: './'
          tags: 'autopilotrpc signrpc walletrpc chainrpc invoicesrpc neutrinorpc routerrpc watchtowerrpc monitoring peersrpc kvdb_postrgres kvdb_sqlite kvdb_etcd'