name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"
  PRERELEASE: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'LND-Desk.AppImage'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'LND-Desk.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'LND-Desk'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Determine PRERELEASE
        id: PRERELEASE
        if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, '-')
        run: |
          echo "PRERELEASE=false" >> $env:GITHUB_ENV

      - name: Build wails
        uses: GEBcore/wails-build-action@v0.1.9
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          prerelease: ${{ env.PRERELEASE }}
          package: true
          wails-version: 'v2.9.3'
          node-version: '22.8.0'
          go-version: '1.24'
          deno-build: 'npm i -g pnpm'
          deno-version: '2.1.4'
          deno-working-directory: './'
          tags: 'autopilotrpc signrpc walletrpc chainrpc invoicesrpc neutrinorpc routerrpc watchtowerrpc monitoring peersrpc kvdb_postrgres kvdb_sqlite kvdb_etcd'
          sign: true
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-cert: ${{ secrets.MACOS_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MACOS_DEVELOPER_CERT_PASSWORD }}
          sign-macos-installer-id: ${{ secrets.MACOS_INSTALLER_CERT_ID }}
          sign-macos-installer-cert: ${{ secrets.MACOS_INSTALLER_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MACOS_INSTALLER_CERT_PASSWORD }}
          sign-macos-apple-username: ${{ secrets.APPLE_USERNAME }}
          sign-macos-apple-provider: ${{ secrets.APPLE_TEAM }}
